version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: vytt-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vytt
      MONGO_INITDB_ROOT_PASSWORD: vytt2024
      MONGO_INITDB_DATABASE: vytt
    volumes:
      - vytt-mongo-data:/data/db

volumes:
  vytt-mongo-data: